#!/bin/bash
set -xe

cd DevOps_Project_2/Terraform

terraform init
terraform plan
terraform $TERRAFORM_ACTION -auto-approve

if [ $TERRAFORM_ACTION = "destroy" ]; then
	exit 0
else
	cd ../Ansible
	ansible-playbook -i /etc/ansible/hosts apache.yaml 
fi
