#!/bin/bash
set -xe

cd DevOps_Project_2/Terraform

#terraform installation
#sudo yum install -y yum-utils
#sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
#sudo yum -y install terraform

#ansible installation
#sudo yum update
#sudo amazon-linux-extras install ansible2
#ansible --version

whoami

terraform init
terraform plan
terraform apply -auto-approve

cd ../Ansible
ansible -m ping all -vvvv

cat apache.yaml 
ansible-playbook -i /etc/ansible/hosts apache.yaml 
